look inside all the values for shiny gold
if it has shiny gold, look inside all the values for its container color
look inside all the values for all the container colors
if its not contained in any other bag, add that color to the array of outer containers
return an array of all the container colors that are not contained

function find outer bags
  // how to deal with restarted at the top of array in recursive call
  keep track of which bags i've checked
  look for a bag that contains current bag
  // switch the if and elseif?
  if (no more bags contain this bag) {
    // would add initial bag color - not good, how to fix?
    add current bag to outer bag list
  } else if (found a new bag that contains this bag){
    find outer bags (new bag)
    continue?
  }
  // need to get back to where I was in the first function
  return list of outer bags

  function find outer bags
    // how to deal with restarted at the top of array in recursive call
    look for a bag that contains current bag
      keep track of which bags i've checked
      if (found a new bag that contains this bag){
        find outer bags (new bag)
      } else
      if (no more bags contain this bag) {
        // would add initial bag color - not good, how to fix?
        if (this bag is NOT my initial bag that I passed in) {
          add current bag to outer bag list
        }
      }
      // need to get back to where I was in the first function
      return list of outer bags

regsArray : {
  "lightsalmon" : ["dottedolive" ,"wavylavender"],
  "darkpurple" : ["stripedmaroon" ,"wavymaroonbag"],
  "mutedlime" : ["drablavender" ,"clearorangebag" ,"stripedblack"],
  "lightgreen" : ["dullgray" ,"darkcrimson"],
  "brightviolet" : ["brightpurplebag"],
  "dottedmagenta" : ["wavybeige" ,"dottedbronzebag"],
  "wavybronze" : ["clearfuchsia"],
  "brightplum" : ["dimviolet"],
  "shinyyellow" : ["clearviolet" ,"drabmaroon"],
  "paletomato" : ["brightaqua"],
  "lightchartreuse" : ["vibrantfuchsia"],
  "mirroredblue" : ["paleaqua"],
  "mutedmaroon" : ["mutedindigo" ,"vibrantgoldbag"],
  "cleargreen" : ["dottedbeige"],
  "mutedindigo" : ["dullgreenbag"],
  "fadedorange" : ["shinygoldbag" ,"dimtomato"],
  "poshpurple" : ["poshturquoise" ,"dulllime" ,"vibrantfuchsia" ,"dullgreen"],
  "dimbeige" : ["dullfuchsia" ,"palesilver" ,"shinysilver"],
  "darktomato" : ["dottedmagenta"],
  "mutedchartreuse" : ["plaidchartreuse" ,"fadedorange"],
  "drabteal" : ["dottedblue" ,"stripedmaroon" ,"dottedtomato" ,"stripedgold"],
  "shinyolive" : ["dimblue" ,"dottedviolet"],
  "brightmagenta" : ["dottedsilver" ,"plaidblack" ,"poshtomato" ,"darksalmon"],
  "stripedcrimson" : ["mutedtomato" ,"mirroredblack" ,"wavyyellow" ,"fadedgreen"],
  "shinybronze" : ["stripedturquoise" ,"lightcoral" ,"stripedaqua" ,"dimbronze"],
  "stripedgray" : ["fadedcoral"],
  "stripedyellow" : ["clearchartreuse" ,"shinyviolet" ,"fadedgold"],
  "cleartan" : ["dimgreen" ,"dullwhite" ,"poshturquoise"],
  "darkbronze" : ["shinypurplebag" ,"darkcoral" ,"plaidgold"],
  "lightorange" : ["cleargreen" ,"mutedblue" ,"drabgray"],
  "wavyturquoise" : ["cleargold" ,"wavytomato" ,"dottedcoral"],
  "drabtan" : ["stripedlimebag" ,"clearorangebag" ,"palewhite" ,"brightyellow"],
  "darkplum" : ["stripedblue" ,"brightfuchsia"],
  "dottedblue" : ["paleaqua" ,"dottedorangebag" ,"dottedindigo" ,"plaidbluebag"],
  "lightwhite" : ["dullred" ,"fadedsalmon"],
  "posholive" : ["shinysilver" ,"darkbronze"],
  "dullolive" : ["darkplum" ,"dottedcoral" ,"clearblue" ,"dullmaroon"],
  "dimtomato" : ["dimchartreuse" ,"shinygold"],
  "clearlavender" : ["lightaqua" ,"dulltan"],
  "wavyteal" : ["dottedbeige"],
  "mirroredorange" : ["palebeige"],
  "dimpurple" : ["stripedgold"],
  "darkchartreuse" : ["wavytomato"],
  "brightcoral" : ["mutedviolet"],
  "drabyellow" : ["darkgoldbag" ,"dottedgold" ,"mirroredchartreuse"],
  "clearorange" : ["brightcyan" ,"dulllavenderbag"],
  "brightbrown" : ["lighttealbag" ,"dottedsalmon"],
  "drabviolet" : ["brightcrimson" ,"wavybronze" ,"wavylavenderbag"],
  "dullturquoise" : ["vibranttomato" ,"lightindigo" ,"shinygreen"],
  "mutedcyan" : ["mutedplum" ,"drabred" ,"mirroredplum"],
  "paleindigo" : ["dimyellow" ,"brightredbag"],
  "vibrantgreen" : ["shinywhite" ,"fadedfuchsia" ,"clearorange"],
  "dottedcrimson" : ["clearfuchsia" ,"cleartanbag"],
  "drabmaroon" : ["mutedolive"],
  "dullbronze" : ["shinyindigo" ,"dimchartreuse"],
  "wavybrown" : ["brighttealbag"],
  "poshblue" : ["stripedblue" ,"drabteal" ,"shinyblack"],
  "clearchartreuse" : ["cleartanbag" ,"dimcyan" ,"drablimebag"],
  "fadedcoral" : ["dottedgreen" ,"plaidcyan" ,"brightcyan"],
  "dottedgreen" : ["drabgray"],
  "wavyorange" : ["stripedcoral" ,"stripedblue" ,"wavygreen"],
  "dottedtomato" : ["lightcrimsonbag" ,"lightlime" ,"vibrantpurple" ,"clearplum"],
  "palefuchsia" : ["mutedorange" ,"dullorange" ,"poshbronze" ,"fadedpurple"],
  "wavylavender" : ["dulllimebag"],
  "dullblue" : ["stripedsilver" ,"brightbrown" ,"dottedgreen" ,"darkbrown"],
  "mutedbeige" : ["dimtomato" ,"shinypurple"],
  "palelime" : ["vibrantcrimsonbag" ,"paleplumbag" ,"mirroredgold" ,"brightchartreuse"],
  "mirroredplum" : ["dimwhite" ,"poshcyan" ,"darklime"],
  "lightcoral" : ["clearsilver" ,"dimgreen" ,"stripedtomatobag"],
  "fadedlavender" : ["darktan" ,"wavytomato" ,"lightcoral" ,"dottedsilver"],
  "plaidlime" : ["lightorange" ,"drabblack" ,"drablime"],
  "vibrantcyan" : ["vibrantgraybag" ,"wavyteal"],
  "darkblue" : ["cleartan" ,"clearsilver" ,"drabblack"],
  "plaidcoral" : ["plaidaqua" ,"drabgold" ,"mirroredplum" ,"dimbronze"],
  "lightmaroon" : ["dimyellow" ,"lightredbag"],
  "plaidsilver" : ["palemaroonbag" ,"shinyblack" ,"darkcoral" ,"poshviolet"],
  "clearviolet" : ["vibrantfuchsia"],
  "clearcyan" : ["plaidyellow" ,"plaidolive" ,"dullgreen"],
  "dimmagenta" : ["wavyplumbag"],
  "drabsalmon" : ["dullwhite" ,"darkbrown"],
  "palemagenta" : ["mutedolivebag" ,"mirroredfuchsia" ,"shinypurple"],
  "drabcoral" : ["stripedsilver"],
  "lightgold" : ["shinyaqua" ,"dimviolet" ,"dottedorange"],
  "shinycyan" : ["mutedaqua" ,"stripedmaroon" ,"lightsalmon"],
  "drabbeige" : ["lightgold" ,"dullwhite"],
  "plaidfuchsia" : ["noother"],
  "vibrantteal" : ["mutedmaroon" ,"poshviolet" ,"cleartan" ,"dullorangebag"],
  "dimcyan" : ["darkturquoisebag"],
  "mirroredchartreuse" : ["dulllavenderbag" ,"palered" ,"plaidchartreuse"],
  "plaidgold" : ["darkturquoise" ,"dimturquoise" ,"plaidfuchsia"],
  "wavygold" : ["lightlime" ,"wavytomato"],
  "wavyred" : ["dottedlavender" ,"dottedblue" ,"stripedbrown" ,"fadedorange"],
  "dullred" : ["drabgreen"],
  "lightred" : ["darkcoral"],
  "wavycrimson" : ["shinygold" ,"drabwhitebag"],
  "drabturquoise" : ["poshgold" ,"paleplum" ,"wavybeige" ,"drabbeige"],
  "dimlavender" : ["darkolive"],
  "shinytan" : ["shinytealbag" ,"cleartanbag" ,"wavybeige" ,"poshcoral"],
  "mirroredfuchsia" : ["brightbrown"],
  "clearwhite" : ["brightcyan" ,"paleorangebag" ,"vibrantgold" ,"dimcyan"],
  "clearmagenta" : ["dullviolet" ,"dullcoral" ,"dullolivebag" ,"palecyanbag"],
  "mirroredsalmon" : ["drabgray" ,"stripedmagentabag"],
  "vibrantcrimson" : ["shinyaqua" ,"fadedbronze"],
  "clearyellow" : ["brightbeige"],
  "stripedolive" : ["clearsilver" ,"dimorange" ,"poshblack" ,"stripedlavender"],
  "paleolive" : ["dottedblue" ,"fadedindigo" ,"palecrimson" ,"cleartan"],
  "stripedwhite" : ["drabsilver" ,"clearbrown"],
  "dottedchartreuse" : ["darkbrown" ,"dimmaroon" ,"plaidchartreuse" ,"darkred"],
  "dimfuchsia" : ["poshindigo" ,"clearpurple"],
  "shinylime" : ["mutedgold" ,"vibrantcrimson" ,"mirroredgreen"],
  "stripedblue" : ["clearcoral" ,"drabgreen" ,"dullgreen"],
  "shinybeige" : ["wavylime"],
  "dimtan" : ["cleargreen" ,"dullgreen"],
  "poshcyan" : ["fadedpurple"],
  "stripedviolet" : ["fadedorange" ,"plaidcrimson" ,"dullfuchsia" ,"brightblack"],
  "mirroredcrimson" : ["drabgraybag" ,"fadedcrimson" ,"dimwhite" ,"dullgreen"],
  "dimorange" : ["dimlime" ,"drabblackbag"],
  "drabcyan" : ["shinysalmon" ,"mutedplum" ,"dottedlavender" ,"plaidgray"],
  "drabbrown" : ["mutedpurple"],
  "mirroredwhite" : ["mirroredcrimson" ,"paleplum" ,"brightmaroon"],
  "vibrantsilver" : ["darkbronze" ,"lightolive" ,"poshcyan"],
  "wavymagenta" : ["mutedaqua" ,"clearbeige" ,"drabbeige" ,"fadedtealbag"],
  "stripedpurple" : ["palecrimson" ,"brightmaroonbag" ,"stripedbronze" ,"palegold"],
  "darkteal" : ["shinyaqua" ,"dullwhitebag" ,"dottedorange" ,"dullgreen"],
  "dottedcoral" : ["darkturquoise"],
  "vibrantlime" : ["dimpurple" ,"shinyblack" ,"dottedblack" ,"mirroredcoralbag"],
  "brightgold" : ["poshtan" ,"drabgray" ,"dottedmaroonbag" ,"clearfuchsia"],
  "darkfuchsia" : ["dullyellow" ,"dimorangebag" ,"mutedbeige"],
  "mutedtomato" : ["poshtealbag" ,"shinyolive"],
  "dullindigo" : ["mutedmaroon"],
  "brightpurple" : ["dottedolivebag" ,"wavychartreusebag" ,"cleartanbag" ,"dottedgreen"],
  "wavyviolet" : ["stripedsilver" ,"paleplumbag"],
  "shinyorange" : ["drabblack" ,"drablime" ,"shinyblack" ,"fadedpurple"],
  "lightbeige" : ["dimcoral" ,"darkwhitebag" ,"lightcrimsonbag" ,"mirroredcoral"],
  "drabtomato" : ["shinyteal" ,"drabbeige" ,"shinypurple"],
  "drablavender" : ["stripedtomato" ,"brightbrownbag"],
  "shinyplum" : ["plaidmagenta" ,"poshindigo" ,"wavyvioletbag" ,"clearwhite"],
  "dottedbrown" : ["mirroredolive" ,"lightyellow" ,"lighttomato"],
  "wavycoral" : ["mirroredplum" ,"poshpurple"],
  "shinymaroon" : ["mutedcyan" ,"wavybluebag" ,"clearlime" ,"plaidorange"],
  "poshbronze" : ["plaidgoldbag" ,"poshyellowbag" ,"wavylime" ,"dullwhite"],
  "brightfuchsia" : ["dullsilver" ,"lightlime"],
  "dullplum" : ["dottedsalmonbag" ,"shinylavender" ,"mirroredpurple" ,"brightcyan"],
  "brightaqua" : ["dullsalmon" ,"plaidcrimsonbag" ,"shinytomato" ,"vibrantfuchsia"],
  "shinysalmon" : ["plaidorange" ,"drabgreen"],
  "mutedcoral" : ["dullindigo" ,"paleplum" ,"dottedblack"],
  "vibrantsalmon" : ["darkturquoise" ,"drabredbag"],
  "dullblack" : ["dullmagentabag"],
  "plaidwhite" : ["shinypurple"],
  "drabgreen" : ["stripedmaroon" ,"darkcrimson" ,"fadedtealbag" ,"dullgreenbag"],
  "fadedpurple" : ["shinygold"],
  "stripedlime" : ["stripedturquoise" ,"clearsilverbag"],
  "clearblack" : ["darkbeige" ,"poshblack"],
  "vibrantpurple" : ["darkbrown"],
  "clearbeige" : ["lighttealbag" ,"plaidfuchsia"],
  "lightlime" : ["drabgray" ,"darkwhitebag" ,"drabtomato" ,"plaidmaroon"],
  "mutedviolet" : ["poshturquoisebag" ,"mirroredwhite"],
  "vibrantolive" : ["clearbeige"],
  "brightsalmon" : ["plaidorangebag"],
  "drabbronze" : ["shinyturquoise" ,"clearfuchsiabag"],
  "drabplum" : ["mutedgold" ,"mirroredturquoise" ,"fadedorange" ,"brightmagenta"],
  "dottedturquoise" : ["stripedmaroon" ,"mirroredviolet" ,"darkfuchsiabag"],
  "wavyolive" : ["vibrantmaroon" ,"shinytan" ,"vibrantyellow" ,"dottedsilver"],
  "wavytomato" : ["palewhitebag" ,"lightyellow"],
  "plaidchartreuse" : ["drabblack"],
  "palechartreuse" : ["mutedpurple" ,"dullgreenbag" ,"darkbrown" ,"lightteal"],
  "dottedcyan" : ["palesalmon"],
  "mutedgold" : ["plaidsilver" ,"dottedorange"],
  "poshorange" : ["poshpurple" ,"darkteal" ,"dottedsilver"],
  "palebrown" : ["fadedteal"],
  "wavyaqua" : ["mutedplum" ,"wavytomato" ,"mirroredgold" ,"drabtan"],
  "brightblue" : ["cleargreen"],
  "dottedred" : ["wavyplum" ,"mutedgreen"],
  "cleartomato" : ["brightcyan" ,"dullgraybag" ,"drabmaroon" ,"mutedindigo"],
  "plaidorange" : ["dottedcoral" ,"palegray" ,"shinyviolet" ,"paleaqua"],
  "mutedteal" : ["mutedmaroon" ,"drabtealbag" ,"lightteal"],
  "wavyblue" : ["palechartreuse" ,"shinywhite" ,"poshteal"],
  "poshteal" : ["palechartreuse"],
  "mirroredmagenta" : ["brightaquabag"],
  "vibrantorange" : ["mirroredmagenta" ,"mirroredvioletbag" ,"poshindigo" ,"fadedorange"],
  "poshblack" : ["brightred"],
  "palewhite" : ["darkteal" ,"dottedsilverbag" ,"cleargreen"],
  "poshtomato" : ["shinyyellowbag" ,"lightblack" ,"drabblue" ,"wavycrimson"],
  "mirroredteal" : ["drabgraybag" ,"lightlime"],
  "mutedgreen" : ["stripedbrown"],
  "dimgold" : ["poshindigo" ,"clearindigo" ,"poshgray"],
  "dullgray" : ["poshorange" ,"shinygold" ,"dimtomatobag" ,"brightcrimson"],
  "stripedgreen" : ["darktan" ,"drabgray" ,"mirroredbrownbag"],
  "clearcoral" : ["stripedbrown" ,"lightlime"],
  "poshbrown" : ["vibrantpurple" ,"darkchartreuse" ,"shinycyan"],
  "dottedblack" : ["brightcrimson" ,"poshorange" ,"lightgold" ,"darkbrown"],
  "poshchartreuse" : ["wavysalmon" ,"stripedsilver" ,"drabviolet"],
  "mirroredtomato" : ["palecrimson"],
  "brightyellow" : ["shinycoralbag" ,"mutedblue" ,"wavybeige"],
  "dullsalmon" : ["brightblue" ,"dullgreen" ,"drabsalmon"],
  "paleblack" : ["shinysalmon"],
  "drabaqua" : ["stripedfuchsia" ,"lightlavender" ,"lightmagentabag"],
  "mutedyellow" : ["stripedplum" ,"fadedbeige" ,"dullsalmonbag" ,"brightred"],
  "stripedbrown" : ["brightred" ,"shinyviolet"],
  "poshwhite" : ["mirroredviolet" ,"mutedsilver"],
  "poshlavender" : ["lightcrimson" ,"palesilver" ,"shinygreen" ,"mirroredsilver"],
  "plaidbeige" : ["mirroredsilver"],
  "dullsilver" : ["dottedsilverbag" ,"drabsalmonbag"],
  "darkviolet" : ["dottedgreen" ,"mutedaquabag" ,"brightchartreuse"],
  "dottedmaroon" : ["clearred" ,"drabblue" ,"vibrantgray"],
  "dimgreen" : ["dottedsilver"],
  "vibrantfuchsia" : ["shinyviolet" ,"dimvioletbag" ,"dottedbeige"],
  "mutedsalmon" : ["dimwhite"],
  "draborange" : ["darkteal"],
  "vibrantviolet" : ["poshcyan" ,"mirroredbrown" ,"darkbeige"],
  "brightcrimson" : ["plaidfuchsiabag" ,"drabblack"],
  "mutedplum" : ["stripedbrown" ,"dullgreen" ,"mirroredbeige"],
  "plaidviolet" : ["dottedindigo"],
  "wavyyellow" : ["plaidlime" ,"mirroredorange"],
  "fadedteal" : ["clearplum" ,"poshpurple" ,"mutedplum" ,"dimtomato"],
  "vibrantbrown" : ["lighttanbag" ,"lightlimebag"],
  "vibrantturquoise" : ["clearbronze" ,"stripedgray" ,"palegreen" ,"vibrantindigo"],
  "darkblack" : ["mirroredgray"],
  "mutedorange" : ["dullorange"],
  "shinyaqua" : ["poshturquoisebag"],
  "poshfuchsia" : ["shinyfuchsia" ,"lightgold"],
  "lightplum" : ["paletealbag" ,"plaidmaroon" ,"drabmaroon"],
  "poshplum" : ["mutedmagenta"],
  "plaidteal" : ["mutedgraybag" ,"clearbronze" ,"paletomato"],
  "paleaqua" : ["poshturquoise" ,"lightchartreuse" ,"palewhitebag" ,"lightgold"],
  "brighttomato" : ["brightyellow" ,"darkred" ,"shinyorangebag" ,"dimtealbag"],
  "lightteal" : ["noother"],
  "darkolive" : ["drabgraybag" ,"stripedteal"],
  "dottedtan" : ["shinysalmon" ,"lightblack" ,"brightred"],
  "lightcyan" : ["clearbeigebag" ,"plaidorange" ,"wavylavender"],
  "darkindigo" : ["mirroredorange" ,"poshbrown"],
  "clearfuchsia" : ["darkredbag" ,"poshblack"],
  "dottedsalmon" : ["palegray"],
  "mirroredturquoise" : ["lightaquabag"],
  "plaidolive" : ["dullsilver" ,"lightblack"],
  "poshcrimson" : ["drabblack" ,"dimteal" ,"lightcyan" ,"darkteal"],
  "dulllime" : ["noother"],
  "drabchartreuse" : ["fadedtanbag"],
  "fadedgray" : ["darkcrimson" ,"lightlavender" ,"dimsilver"],
  "wavyindigo" : ["mutedchartreuse" ,"dimgreen" ,"lightfuchsia" ,"shinywhite"],
  "lighttan" : ["lightolivebag" ,"dimcyanbag" ,"plaidorange"],
  "lightfuchsia" : ["shinyindigo" ,"wavycoral" ,"wavytomato"],
  "dullyellow" : ["fadedcoral" ,"dimwhite" ,"dullwhite"],
  "drabmagenta" : ["mutedviolet" ,"lightplum" ,"fadedorange"],
  "mirroredgray" : ["wavycyan" ,"drabtealbag" ,"clearredbag" ,"brightlavender"],
  "dullcoral" : ["brightyellowbag" ,"dullviolet" ,"darkorange" ,"brightgreen"],
  "mirroredolive" : ["drabplumbag" ,"plaidorange"],
  "mutedolive" : ["shinygold" ,"shinyaqua" ,"wavychartreuse" ,"wavylavender"],
  "cleargold" : ["brightpurple" ,"lightcyan" ,"wavytomato"],
  "plaidgreen" : ["shinyyellow" ,"lightsalmon" ,"lightsilver" ,"dimpurple"],
  "poshred" : ["darkviolet"],
  "mutedpurple" : ["drabsalmon"],
  "vibrantaqua" : ["clearbeige" ,"vibrantsilver" ,"fadedolivebag"],
  "stripedindigo" : ["plaidbrown" ,"lightaqua" ,"paletomato"],
  "wavytan" : ["fadedindigo" ,"vibrantchartreusebag" ,"drabbeige" ,"drabgold"],
  "shinygold" : ["wavychartreuse"],
  "wavypurple" : ["fadedmaroon" ,"palemagenta"],
  "mirroredindigo" : ["plaidblack" ,"darkteal" ,"dullindigo"],
  "plaidcrimson" : ["dottedgreen" ,"dullwhite"],
  "darkaqua" : ["wavycoralbag" ,"plaidcrimsonbag"],
  "shinyfuchsia" : ["darkolivebag" ,"wavysilver" ,"brightturquoise" ,"dullwhitebag"],
  "stripedorange" : ["dottedgreen" ,"mirroredcoralbag" ,"dullindigo"],
  "drabpurple" : ["poshorangebag" ,"brightbluebag"],
  "dullorange" : ["dimindigo" ,"paleorange"],
  "paleplum" : ["lightyellow"],
  "palecyan" : ["drabsalmon" ,"dullmagenta" ,"clearplumbag" ,"fadedtomatobag"],
  "dottedindigo" : ["mirroredbeigebag" ,"drabblackbag" ,"shinyaqua"],
  "shinylavender" : ["mutedbeigebag" ,"brightcyan" ,"dullgreen"],
  "drablime" : ["drabblack" ,"dottedsalmon"],
  "mirroredbronze" : ["dimbronze" ,"stripedtan" ,"clearmaroon" ,"dottedcoral"],
  "shinybrown" : ["stripedgold" ,"vibrantsilverbag" ,"shinygold"],
  "stripedchartreuse" : ["vibrantgray" ,"darkcyanbag"],
  "mutedblack" : ["plaidindigo"],
  "mutedaqua" : ["paleredbag" ,"paleaqua"],
  "brightmaroon" : ["drabblack" ,"clearvioletbag" ,"dottedlavenderbag" ,"mirroredturquoisebag"],
  "vibrantchartreuse" : ["palesilver"],
  "dullpurple" : ["mirroredchartreuse"],
  "clearbrown" : ["lightcoral" ,"plaidcyan" ,"dimbrown"],
  "shinyteal" : ["drabblack" ,"shinysilver" ,"mutedpurple"],
  "dullaqua" : ["dottedlime" ,"mirroredlime"],
  "wavygreen" : ["stripedbrownbag" ,"stripedturquoise" ,"dullsilver" ,"drabwhite"],
  "cleargray" : ["paletan" ,"poshtomato" ,"darkbrown" ,"stripedvioletbag"],
  "brightcyan" : ["drabsalmon" ,"lightcrimson"],
  "clearsilver" : ["mirroredturquoise" ,"poshorange" ,"lightgold" ,"cleargreen"],
  "palepurple" : ["dottedbeige" ,"poshorange"],
  "stripedtomato" : ["dottedgreenbag" ,"darkturquoise"],
  "mutedtan" : ["fadedgreen" ,"dimcyan"],
  "darkcoral" : ["dimchartreuse" ,"stripedplumbag"],
  "shinywhite" : ["poshorange"],
  "dimolive" : ["fadedtealbag" ,"palelime" ,"dimteal"],
  "fadedblack" : ["palecyan" ,"dullgray" ,"lightteal" ,"shinybronze"],
  "lightindigo" : ["dimcyan" ,"shinysilverbag" ,"dulllavender"],
  "dimcoral" : ["stripedsilver" ,"dimtomato"],
  "plaidtan" : ["mirroredturquoise" ,"dimbeige" ,"shinylavender" ,"dimbronze"],
  "stripedplum" : ["wavylavender" ,"drabwhitebag"],
  "fadedwhite" : ["dimcoralbag"],
  "dottedlime" : ["mutedgold" ,"shinyviolet" ,"plaidviolet" ,"wavybronzebag"],
  "dottedviolet" : ["poshorangebag" ,"plaidfuchsia"],
  "dullgold" : ["vibrantcrimson" ,"drabbronzebag" ,"dottedtan"],
  "brightred" : ["palewhite" ,"lightchartreuse" ,"clearbeige" ,"dottedgreen"],
  "wavycyan" : ["dottedchartreuse" ,"wavyvioletbag" ,"poshcoralbag" ,"dottedbronze"],
  "fadedfuchsia" : ["poshmaroon" ,"clearplum" ,"drablime"],
  "dimviolet" : ["noother"],
  "stripedbronze" : ["dimorange" ,"darkorangebag" ,"darksalmonbag" ,"fadedteal"],
  "drabolive" : ["stripedviolet" ,"palebeige"],
  "mutedred" : ["paleaqua" ,"wavycyanbag" ,"clearwhite" ,"drabredbag"],
  "shinyblue" : ["plaidaqua" ,"drabsalmon" ,"paletan" ,"vibrantcyan"],
  "dottedolive" : ["darkbrown"],
  "shinysilver" : ["lightgold" ,"brightcrimson" ,"darkturquoise"],
  "darkbeige" : ["mirroredredbag" ,"darksalmon" ,"stripedsilver" ,"plaidorange"],
  "plaidred" : ["wavyfuchsia" ,"shinyturquoise" ,"shinycoralbag"],
  "mirroredbeige" : ["plaidcrimsonbag" ,"dottedbeige" ,"clearbeige" ,"mutedblue"],
  "dimplum" : ["stripedcyan" ,"shinybeige" ,"vibrantolive" ,"lightmaroon"],
  "dottedbeige" : ["shinyviolet" ,"dimviolet" ,"dullwhite" ,"plaidfuchsia"],
  "palebeige" : ["lightaqua"],
  "dimgray" : ["dottedindigo" ,"dimcoral"],
  "lightpurple" : ["shinybrown" ,"drabviolet" ,"stripedtomatobag"],
  "darksalmon" : ["dimgreenbag" ,"dimtan"],
  "mirroredlime" : ["lightgold" ,"drabtan"],
  "clearblue" : ["drabtomato" ,"paleolive"],
  "plaidlavender" : ["shinyindigo" ,"mutedcrimson" ,"mirroredlime"],
  "vibranttomato" : ["drabsalmon" ,"fadedpurple" ,"fadedbronzebag" ,"brightfuchsia"],
  "poshturquoise" : ["dimchartreusebag"],
  "clearturquoise" : ["mutedindigo" ,"darkmaroonbag" ,"dullcoral"],
  "drabcrimson" : ["plaidturquoisebag" ,"fadedsalmon"],
  "darkbrown" : ["noother"],
  "fadedtomato" : ["lightcyan" ,"lightmaroonbag"],
  "clearplum" : ["drablavender"],
  "brightwhite" : ["dimtan" ,"fadedorangebag" ,"dimaquabag"],
  "shinygreen" : ["dottedcoral" ,"mirroredwhitebag" ,"shinygray"],
  "clearolive" : ["mirroredteal"],
  "stripedred" : ["palegreenbag" ,"lightmaroon"],
  "dulltomato" : ["mirroredwhite" ,"poshbronze"],
  "lightsilver" : ["mirroredplumbag" ,"dimteal"],
  "stripedteal" : ["lightbronze"],
  "mirroredtan" : ["lightgold" ,"poshbrown"],
  "clearpurple" : ["clearmagenta" ,"paletomato" ,"lightblack"],
  "fadedgreen" : ["lightgreen" ,"plaidbronze"],
  "shinyred" : ["darkwhite" ,"poshgreen" ,"shinyindigo"],
  "mutedwhite" : ["dottedcoral" ,"wavyblue"],
  "dimcrimson" : ["wavyblue" ,"palegray"],
  "stripedlavender" : ["darkblue" ,"paleaqua" ,"stripedturquoise" ,"darkcoral"],
  "wavygray" : ["mutedgray" ,"palesilverbag" ,"mutedblue" ,"paletomato"],
  "mirroredsilver" : ["mirroredblack" ,"mirroredplum" ,"stripedsilver" ,"dottedgreen"],
  "lightcrimson" : ["fadedmaroon" ,"dimchartreuse" ,"dottedviolet"],
  "shinycoral" : ["shinysilver" ,"poshyellow" ,"plaidblue" ,"shinyaqua"],
  "palered" : ["drabwhite" ,"dottedsilverbag" ,"drabsalmon" ,"dullgreen"],
  "poshmaroon" : ["dimgreenbag"],
  "poshgold" : ["palegreenbag" ,"stripedsilver"],
  "lightblue" : ["dottedsilver" ,"mutedbeigebag"],
  "palelavender" : ["vibrantorange" ,"dullchartreuse"],
  "fadedgold" : ["shinygray"],
  "brightorange" : ["poshteal" ,"wavygreen" ,"brightchartreusebag" ,"darkwhite"],
  "mirroredviolet" : ["palewhite" ,"darkbrown" ,"brightblue"],
  "dimwhite" : ["cleargreen"],
  "lightaqua" : ["noother"],
  "dullchartreuse" : ["stripedgold"],
  "clearsalmon" : ["palesalmon"],
  "brightolive" : ["poshbluebag"],
  "brightlavender" : ["palelime"],
  "paleturquoise" : ["mutedchartreuse"],
  "vibrantwhite" : ["lightred"],
  "dottedsilver" : ["darkbrownbag" ,"darkturquoise" ,"dimviolet"],
  "dullgreen" : ["lightteal" ,"drabblack"],
  "wavyplum" : ["paleindigo" ,"plaidyellow" ,"wavygreenbag" ,"mutedgreen"],
  "vibrantyellow" : ["brightbeige" ,"dimbrown" ,"dottedteal"],
  "fadedbeige" : ["dimbrown" ,"cleargold"],
  "dottedpurple" : ["shinywhite"],
  "mirroredgreen" : ["darkred" ,"drabviolet" ,"brightlavender"],
  "shinytomato" : ["stripedlavender"],
  "brightsilver" : ["dottedmagentabag" ,"dimgreen" ,"mutedcoralbag" ,"shinyteal"],
  "plaidmaroon" : ["dimbrown"],
  "dimsalmon" : ["paleolive" ,"darkcrimson"],
  "darkgold" : ["darkorange" ,"brightfuchsia" ,"dullsalmonbag" ,"darkblue"],
  "stripedcyan" : ["plaidblue" ,"darkorangebag" ,"clearviolet"],
  "darkgray" : ["lightorange"],
  "poshgray" : ["plaidmaroonbag" ,"drabgold" ,"mutedgoldbag" ,"lightbronze"],
  "palegold" : ["clearorange" ,"dimorange"],
  "paleteal" : ["poshtealbag" ,"palered"],
  "vibrantlavender" : ["plaidsilver" ,"clearorange" ,"poshsilver" ,"wavyvioletbag"],
  "dimblack" : ["darkplum" ,"plaidturquoise" ,"dullsalmon" ,"clearorange"],
  "darkwhite" : ["vibrantfuchsia"],
  "darkred" : ["shinyviolet" ,"vibrantfuchsia" ,"palecrimsonbag"],
  "stripedsilver" : ["poshpurple" ,"darkwhite"],
  "stripedturquoise" : ["brightbrownbag" ,"dottedgreen"],
  "wavysalmon" : ["lightteal"],
  "mutedturquoise" : ["brightgraybag" ,"plaidorange" ,"mutedblue" ,"dottedolive"],
  "wavyblack" : ["mirroredblack" ,"stripedplum" ,"dulllimebag" ,"poshteal"],
  "stripedtan" : ["palegreen"],
  "darkturquoise" : ["shinyviolet" ,"darkbrown"],
  "plaidblack" : ["plaidcrimson" ,"dimturquoise" ,"dottedblack"],
  "lightturquoise" : ["plaidchartreuse" ,"dullviolet"],
  "plaidgray" : ["lightyellowbag" ,"stripedlavender" ,"wavychartreuse" ,"dottedsalmon"],
  "drabblack" : ["noother"],
  "plaidcyan" : ["dimtanbag" ,"plaidgold" ,"drabgraybag"],
  "brighttan" : ["plaidolivebag" ,"mirroredblack"],
  "fadedbrown" : ["dottedtomato"],
  "dottedfuchsia" : ["drabsilver"],
  "drabwhite" : ["shinyviolet"],
  "poshsalmon" : ["stripedturquoise"],
  "dullmaroon" : ["fadedindigo"],
  "brightbronze" : ["mutedbluebag" ,"darkchartreuse" ,"wavypurple" ,"vibrantviolet"],
  "plaidbronze" : ["darkbrownbag"],
  "darklavender" : ["dimyellow" ,"drabred" ,"brightturquoise" ,"shinyblack"],
  "wavysilver" : ["lightyellowbag" ,"palered"],
  "paletan" : ["dullorange" ,"dottedolive" ,"vibrantpurple" ,"dulltan"],
  "paleorange" : ["lightteal" ,"dimmaroonbag"],
  "shinyindigo" : ["drabmaroon" ,"dottedindigo" ,"brightpurplebag" ,"stripedbrown"],
  "mutedfuchsia" : ["poshcrimson" ,"clearbeige"],
  "plaidplum" : ["clearsilverbag" ,"lightcyan" ,"vibrantgraybag" ,"drabpurple"],
  "fadedviolet" : ["dottedbeige" ,"mutedaqua"],
  "dottedplum" : ["plaidbrown" ,"wavygreen" ,"darkcyan" ,"palered"],
  "vibranttan" : ["cleargray"],
  "drabsilver" : ["dullchartreuse"],
  "shinyturquoise" : ["darkolive"],
  "darksilver" : ["dottedblack"],
  "stripedbeige" : ["stripedmagenta"],
  "dottedorange" : ["lightaquabag" ,"poshturquoise"],
  "shinymagenta" : ["drabsalmon" ,"mirroredorange"],
  "poshmagenta" : ["plaidfuchsia" ,"dimmaroon"],
  "clearbronze" : ["wavyfuchsiabag" ,"vibrantblack"],
  "dullviolet" : ["mutedindigobag" ,"poshgreen" ,"stripedwhite" ,"clearredbag"],
  "poshlime" : ["vibrantcyan"],
  "palesilver" : ["darkcrimson" ,"lightsalmonbag" ,"clearbrownbag"],
  "poshyellow" : ["dimwhitebag" ,"palecrimson"],
  "vibrantbronze" : ["fadedgray" ,"dimgraybag" ,"poshcyan" ,"plaidlavender"],
  "dullbeige" : ["wavyfuchsia" ,"plaidcrimson" ,"darkblue" ,"wavysilverbag"],
  "dullbrown" : ["paleturquoise" ,"cleartan"],
  "fadedturquoise" : ["plaidgold" ,"wavychartreuse"],
  "darkyellow" : ["wavylavenderbag" ,"darkcoral"],
  "dottedgray" : ["poshpurple" ,"wavylavender" ,"shinygreen" ,"plaidwhite"],
  "dimaqua" : ["dulllimebag"],
  "poshviolet" : ["mirroredtomatobag" ,"poshcyan"],
  "shinygray" : ["cleargreen" ,"wavybronzebag" ,"darkturquoise" ,"palewhite"],
  "drabred" : ["mirroredviolet" ,"dottedorange" ,"darklime" ,"brightpurple"],
  "stripedmagenta" : ["stripedbrown"],
  "dullmagenta" : ["dimtomato" ,"mutedbeige" ,"clearviolet"],
  "clearmaroon" : ["plaidlime"],
  "poshsilver" : ["mirroredred"],
  "darkcrimson" : ["mirroredviolet"],
  "palemaroon" : ["shinyblack"],
  "darkmagenta" : ["darkgreenbag" ,"lightplum"],
  "brightlime" : ["paleindigobag" ,"dimyellow" ,"drabmaroon" ,"lightplum"],
  "darkorange" : ["wavylavenderbag" ,"dottedorangebag" ,"lightcrimson" ,"lightyellow"],
  "wavylime" : ["clearblue" ,"mutedbrown" ,"mirroredviolet" ,"dottedlavender"],
  "dottedlavender" : ["poshtealbag" ,"darkred" ,"palegraybag"],
  "mutedbrown" : ["darkwhitebag" ,"dullmaroon" ,"fadedmaroonbag"],
  "dimyellow" : ["darkwhite"],
  "fadedtan" : ["lightcoral" ,"lightyellow"],
  "fadedcrimson" : ["plaidfuchsia" ,"plaidorange"],
  "palesalmon" : ["palered" ,"dottedolive" ,"plaidmagenta"],
  "dimbronze" : ["mutedplum" ,"lightcyan" ,"darkcoral"],
  "brightteal" : ["vibrantviolet" ,"stripedbronze" ,"stripedvioletbag" ,"darkgray"],
  "palebronze" : ["plaidbrown" ,"plaidwhitebag"],
  "vibrantplum" : ["drabtan" ,"plaidyellow" ,"fadedfuchsia"],
  "dottedteal" : ["fadedcoral" ,"fadedindigo" ,"poshvioletbag" ,"paleindigo"],
  "plaidsalmon" : ["darklavender" ,"poshbronze" ,"lightcoral" ,"poshorangebag"],
  "dimred" : ["lightviolet"],
  "drabgold" : ["wavysilver" ,"lightbronze"],
  "shinyviolet" : ["noother"],
  "mirroredmaroon" : ["drabyellowbag" ,"wavybeige"],
  "dottedaqua" : ["mutedplum"],
  "fadedsalmon" : ["mirroredolive" ,"dimlavender"],
  "lightviolet" : ["wavysalmon"],
  "plaidbrown" : ["fadedindigo"],
  "mirroredcoral" : ["palegray"],
  "mutedlavender" : ["poshbeigebag" ,"clearsilver" ,"dottedbronzebag"],
  "brightturquoise" : ["stripedblack" ,"dullmaroon"],
  "vibrantgold" : ["brightpurple" ,"brightredbag"],
  "mutedmagenta" : ["clearvioletbag" ,"mutedlavender" ,"fadedaqua"],
  "fadedsilver" : ["poshbrown" ,"mirroredsilver"],
  "dimteal" : ["dimviolet" ,"darkwhitebag" ,"dottedblack"],
  "stripedmaroon" : ["shinywhite"],
  "darkmaroon" : ["plaidsilver" ,"dullredbag" ,"shinycoral" ,"brightwhite"],
  "clearcrimson" : ["mutedsalmon" ,"cleargreen" ,"lightbluebag" ,"poshmagenta"],
  "dottedyellow" : ["vibrantcoral"],
  "lighttomato" : ["dimchartreuse" ,"lightgold" ,"darkwhite"],
  "shinypurple" : ["darkturquoise"],
  "brightgreen" : ["lightchartreusebag"],
  "mirroredyellow" : ["stripedwhite"],
  "lightlavender" : ["wavycrimsonbag" ,"dimyellow" ,"plaidolivebag" ,"wavywhite"],
  "mutedcrimson" : ["darkbeige" ,"dullgreenbag"],
  "mutedblue" : ["shinyaqua" ,"darkturquoise" ,"dottedsilverbag"],
  "stripedcoral" : ["darkred" ,"drabbluebag" ,"lightaqua" ,"stripedlavenderbag"],
  "lightbrown" : ["plaidyellow"],
  "clearaqua" : ["plaidolivebag" ,"plaidgoldbag" ,"mutedtanbag"],
  "dottedgold" : ["darkwhite"],
  "plaidblue" : ["dottedcoral" ,"mutedblue"],
  "mirroredcyan" : ["darkwhite" ,"stripedturquoisebag" ,"lightcoral"],
  "fadedred" : ["cleartan" ,"stripedbrown" ,"shinycyan"],
  "clearlime" : ["clearsilver"],
  "dimlime" : ["lightteal" ,"poshturquoisebag" ,"dottedsilver" ,"drablavenderbag"],
  "dullteal" : ["lightmaroonbag" ,"brightcoral"],
  "lightgray" : ["mirroredlime" ,"lightviolet" ,"mutedolivebag" ,"stripedbrown"],
  "dottedwhite" : ["wavywhite" ,"dottedbeigebag" ,"cleargreen"],
  "shinycrimson" : ["palesalmon" ,"darklime" ,"dullblue" ,"vibrantchartreusebag"],
  "dimbrown" : ["mirroredbeige" ,"lightorange" ,"fadedcrimson"],
  "dimblue" : ["palegray"],
  "stripedblack" : ["vibrantpurple" ,"vibrantsalmon" ,"cleargold" ,"shinyyellow"],
  "stripedfuchsia" : ["plaidfuchsia" ,"poshteal" ,"drabtomato" ,"dimturquoise"],
  "shinyblack" : ["stripedtomato"],
  "vibrantmaroon" : ["brightaqua" ,"poshwhitebag" ,"palesilverbag" ,"mutedtan"],
  "poshcoral" : ["mirroredviolet" ,"mirroredbeige" ,"stripedtomato" ,"drabwhite"],
  "wavychartreuse" : ["mutedblue" ,"brightcrimsonbag" ,"palegraybag" ,"shinysilverbag"],
  "brightchartreuse" : ["stripedbrown"],
  "brightgray" : ["drabgray" ,"plaidcyan" ,"drabmaroonbag"],
  "darklime" : ["cleargreen" ,"dottedwhite"],
  "fadedmaroon" : ["shinygold" ,"dottedgreen" ,"stripedbrown"],
  "dimsilver" : ["mutedtomato" ,"mirroredviolet"],
  "fadedchartreuse" : ["palegray" ,"stripedcyan"],
  "poshbeige" : ["fadedblue"],
  "stripedaqua" : ["brightgray" ,"shinyaqua" ,"shinygray"],
  "dulltan" : ["dottedgreen" ,"lightcrimson" ,"mirroredfuchsia" ,"shinycyan"],
  "darkgreen" : ["drabyellow"],
  "wavyfuchsia" : ["wavygray" ,"fadedfuchsiabag" ,"brightmaroon"],
  "vibrantindigo" : ["dottedtomato" ,"lightcoral" ,"darksilverbag"],
  "drabindigo" : ["palecoral"],
  "fadedindigo" : ["vibrantfuchsia" ,"wavycoralbag" ,"stripedteal"],
  "paleviolet" : ["palelime" ,"poshindigo" ,"mutedblue" ,"plaidcyan"],
  "drabblue" : ["dullsilver" ,"dottedbeige" ,"mutedaquabag" ,"dottedorange"],
  "dullcrimson" : ["dimbrown" ,"mirroredblackbag"],
  "mirroredlavender" : ["poshchartreuse" ,"vibrantbluebag" ,"dullmagenta"],
  "lightolive" : ["dottedsilver" ,"dimwhite" ,"paleteal"],
  "vibrantblue" : ["darkfuchsiabag" ,"dimteal"],
  "dimchartreuse" : ["noother"],
  "brightblack" : ["dulllavenderbag" ,"darkteal" ,"plaidblue" ,"darkwhite"],
  "darkcyan" : ["lightbeige" ,"brightorange"],
  "lightyellow" : ["stripedsilver" ,"darkbrown" ,"dottedsalmon" ,"dimviolet"],
  "dottedbronze" : ["dimblue" ,"darkchartreuse"],
  "fadedyellow" : ["fadedfuchsiabag" ,"darkbrown" ,"mutedsalmonbag"],
  "dullfuchsia" : ["brightturquoisebag" ,"drabgreenbag"],
  "fadedblue" : ["dullchartreuse" ,"shinyvioletbag"],
  "stripedgold" : ["dullsilver" ,"dottedblack"],
  "mirroredblack" : ["wavytomatobag" ,"poshviolet" ,"vibrantcrimson" ,"dulllimebag"],
  "poshtan" : ["plaidolive" ,"dottedwhite"],
  "vibrantblack" : ["lightchartreusebag" ,"darkorange"],
  "dimindigo" : ["plaidcrimsonbag"],
  "mirroredred" : ["fadedmaroon"],
  "vibrantbeige" : ["fadedteal" ,"shinycoral" ,"drabteal"],
  "drabgray" : ["lightteal" ,"dullwhitebag"],
  "paleblue" : ["poshpurplebag" ,"lightcyan"],
  "poshindigo" : ["dimgray" ,"stripedmaroon" ,"drabwhite" ,"lighttomato"],
  "dimmaroon" : ["palewhite"],
  "fadedaqua" : ["drabwhite" ,"fadedpurple" ,"stripedmaroon"],
  "plaidaqua" : ["stripedturquoisebag" ,"lightbronze" ,"palechartreuse"],
  "dulllavender" : ["stripedplum" ,"dottedwhitebag" ,"dottedsalmon" ,"dullsilver"],
  "lightmagenta" : ["drabviolet" ,"drabcoral" ,"vibrantlavender" ,"dullolive"],
  "fadedlime" : ["mirroredcoral" ,"wavylavender" ,"lightyellow" ,"shinysilverbag"],
  "wavywhite" : ["drabwhite"],
  "clearindigo" : ["dimcyan"],
  "plaidturquoise" : ["drabwhite" ,"darkteal" ,"plaidfuchsia"],
  "plaidtomato" : ["drabviolet" ,"stripedsalmon"],
  "brightbeige" : ["shinyblack" ,"poshsalmon" ,"stripedbronze" ,"paleplum"],
  "vibrantred" : ["palefuchsia"],
  "poshgreen" : ["drabredbag"],
  "fadedplum" : ["plaidchartreuse" ,"brightbronze" ,"darkblue" ,"clearbronze"],
  "dimturquoise" : ["lightchartreuse"],
  "clearred" : ["drabbluebag" ,"stripedfuchsia" ,"stripedbrown" ,"clearsilver"],
  "palegray" : ["dullgreenbag" ,"dottedorange" ,"darkturquoise"],
  "plaidpurple" : ["dimcyanbag" ,"stripedlime" ,"drabviolet"],
  "clearteal" : ["dullcyan" ,"wavycyanbag" ,"lightblue"],
  "mirroredbrown" : ["mirroredred"],
  "lightbronze" : ["wavywhitebag"],
  "mutedgray" : ["fadedlime" ,"palebeigebag" ,"shinyindigobag" ,"fadedtanbag"],
  "stripedsalmon" : ["dimteal" ,"dottedsilver" ,"dimgray"],
  "brightindigo" : ["drabbeige" ,"shinyredbag" ,"vibrantsilver" ,"clearplum"],
  "palecoral" : ["wavyplum" ,"clearbeige"],
  "fadedolive" : ["brightcrimson" ,"dottedgreen" ,"dullbronze" ,"poshturquoise"],
  "wavymaroon" : ["mirroredfuchsia" ,"dimolive"],
  "plaidindigo" : ["poshmagenta" ,"dimbronzebag" ,"lightbluebag"],
  "poshaqua" : ["clearbeige" ,"darklime"],
  "fadedcyan" : ["drabtomatobag" ,"poshcrimson" ,"palechartreuse" ,"fadedtan"],
  "plaidyellow" : ["wavycyan" ,"stripedblack"],
  "fadedmagenta" : ["brightcoral"],
  "dullcyan" : ["mirroredmagenta" ,"clearchartreuse"],
  "vibrantcoral" : ["dottedaqua" ,"brightcyanbag"],
  "mirroredgold" : ["shinypurple"],
  "mirroredpurple" : ["darkbeige"],
  "paleyellow" : ["plaidcoral" ,"wavysilver" ,"mirroredsalmonbag" ,"lightlime"],
  "darktan" : ["lightyellowbag" ,"plaidturquoise" ,"shinygold"],
  "fadedbronze" : ["stripedgold" ,"poshtealbag"],
  "lightblack" : ["shinyblack" ,"mirroredcoral"],
  "vibrantgray" : ["darkteal" ,"mutedaqua" ,"shinyviolet" ,"darkbronze"],
  "wavybeige" : ["palemaroon"],
  "mutedsilver" : ["plaidorange" ,"shinychartreusebag"],
  "plaidmagenta" : ["dottedtanbag" ,"stripedfuchsia" ,"lightolive"],
  "drabfuchsia" : ["darkviolet" ,"shinygoldbag" ,"palecyan"],
  "shinychartreuse" : ["dottedviolet"],
  "palecrimson" : ["paleaqua"],
  "dullwhite" : ["noother"],
  "palegreen" : ["brightgreen" ,"dulllime" ,"stripedlimebag"],
  "mutedbronze" : ["brighttomato" ,"lightred" ,"shinyyellow" ,"dimteal"],
  "mirroredaqua" : ["dimtomato" ,"mirroredcrimsonbag" ,"wavysilverbag"],
  "vibrantmagenta" : ["darklime"]
},
