function findInnerBags(colorString, rules) {
  let allInnerBagsCount = 0;
  let ruleDetails = rules[colorString];
    let keys = Object.keys(ruleDetails);
    for (let k=0; k < keys.length; k++) {
      let innerBagsCount = findInnerBags(keys[k], rules);
      allInnerBagsCount += ruleDetails[keys[k]];
      allInnerBagsCount += ruleDetails[keys[k]]*innerBagsCount;
    }
  return allInnerBagsCount;
}

regsArray = {
  "light salmon": {"dotted olive": 5, "wavy lavender": 4},
  "dark purple": {"striped maroon": 5, "wavy maroon": 1},
  "muted lime": {"drab lavender": 4, "clear orange": 1, "striped black": 2},
  "light green": {"dull gray": 5, "dark crimson": 3},
  "bright violet": {"bright purple": 1},
  "dotted magenta": {"wavy beige": 2, "dotted bronze": 1},
  "wavy bronze": {"clear fuchsia": 4},
  "bright plum": {"dim violet": 2},
  "shiny yellow": {"clear violet": 5, "drab maroon": 3},
  "pale tomato": {"bright aqua": 3},
  "light chartreuse": {"vibrant fuchsia": 3},
  "mirrored blue": {"pale aqua": 2},
  "muted maroon": {"muted indigo": 3, "vibrant gold": 1},
  "clear green": {"dotted beige": 4},
  "muted indigo": {"dull green": 1},
  "faded orange": {"shiny gold": 1, "dim tomato": 4},
  "posh purple": {"posh turquoise": 3, "dull lime": 4, "vibrant fuchsia": 3, "dull green": 2},
  "dim beige": {"dull fuchsia": 4, "pale silver": 5, "shiny silver": 3},
  "dark tomato": {"dotted magenta": 5},
  "muted chartreuse": {"plaid chartreuse": 2, "faded orange": 3},
  "drab teal": {"dotted blue": 2, "striped maroon": 2, "dotted tomato": 5, "striped gold": 5},
  "shiny olive": {"dim blue": 5, "dotted violet": 3},
  "bright magenta": {"dotted silver": 2, "plaid black": 4, "posh tomato": 4, "dark salmon": 4},
  "striped crimson": {"muted tomato": 3, "mirrored black": 2, "wavy yellow": 2, "faded green": 2},
  "shiny bronze": {"striped turquoise": 5, "light coral": 5, "striped aqua": 4, "dim bronze": 5},
  "striped gray": {"faded coral": 2},
  "striped yellow": {"clear chartreuse": 4, "shiny violet": 2, "faded gold": 2},
  "clear tan": {"dim green": 4, "dull white": 3, "posh turquoise": 2},
  "dark bronze": {"shiny purple": 1, "dark coral": 2, "plaid gold": 5},
  "light orange": {"clear green": 3, "muted blue": 2, "drab gray": 3},
  "wavy turquoise": {"clear gold": 3, "wavy tomato": 5, "dotted coral": 5},
  "drab tan": {"striped lime": 1, "clear orange": 1, "pale white": 3, "bright yellow": 3},
  "dark plum": {"striped blue": 2, "bright fuchsia": 4},
  "dotted blue": {"pale aqua": 2, "dotted orange": 1, "dotted indigo": 4, "plaid blue": 1},
  "light white": {"dull red": 5, "faded salmon": 4},
  "posh olive": {"shiny silver": 4, "dark bronze": 5},
  "dull olive": {"dark plum": 4, "dotted coral": 2, "clear blue": 4, "dull maroon": 2},
  "dim tomato": {"dim chartreuse": 2, "shiny gold": 3},
  "clear lavender": {"light aqua": 5, "dull tan": 5},
  "wavy teal": {"dotted beige": 4},
  "mirrored orange": {"pale beige": 2},
  "dim purple": {"striped gold": 2},
  "dark chartreuse": {"wavy tomato": 2},
  "bright coral": {"muted violet": 4},
  "drab yellow": {"dark gold": 1, "dotted gold": 5, "mirrored chartreuse": 3},
  "clear orange": {"bright cyan": 3, "dull lavender": 1},
  "bright brown": {"light teal": 1, "dotted salmon": 4},
  "drab violet": {"bright crimson": 5, "wavy bronze": 2, "wavy lavender": 1},
  "dull turquoise": {"vibrant tomato": 3, "light indigo": 4, "shiny green": 4},
  "muted cyan": {"muted plum": 5, "drab red": 3, "mirrored plum": 5},
  "pale indigo": {"dim yellow": 4, "bright red": 1},
  "vibrant green": {"shiny white": 3, "faded fuchsia": 3, "clear orange": 4},
  "dotted crimson": {"clear fuchsia": 5, "clear tan": 1},
  "drab maroon": {"muted olive": 4},
  "dull bronze": {"shiny indigo": 5, "dim chartreuse": 2},
  "wavy brown": {"bright teal": 1},
  "posh blue": {"striped blue": 3, "drab teal": 3, "shiny black": 5},
  "clear chartreuse": {"clear tan": 1, "dim cyan": 2, "drab lime": 1},
  "faded coral": {"dotted green": 4, "plaid cyan": 3, "bright cyan": 2},
  "dotted green": {"drab gray": 4},
  "wavy orange": {"striped coral": 5, "striped blue": 5, "wavy green": 5},
  "dotted tomato": {"light crimson": 1, "light lime": 5, "vibrant purple": 3, "clear plum": 5},
  "pale fuchsia": {"muted orange": 2, "dull orange": 3, "posh bronze": 4, "faded purple": 2},
  "wavy lavender": {"dull lime": 1},
  "dull blue": {"striped silver": 5, "bright brown": 5, "dotted green": 5, "dark brown": 3},
  "muted beige": {"dim tomato": 5, "shiny purple": 2},
  "pale lime": {"vibrant crimson": 1, "pale plum": 1, "mirrored gold": 4, "bright chartreuse": 3},
  "mirrored plum": {"dim white": 2, "posh cyan": 3, "dark lime": 3},
  "light coral": {"clear silver": 4, "dim green": 5, "striped tomato": 1},
  "faded lavender": {"dark tan": 2, "wavy tomato": 2, "light coral": 2, "dotted silver": 5},
  "plaid lime": {"light orange": 3, "drab black": 5, "drab lime": 2},
  "vibrant cyan": {"vibrant gray": 1, "wavy teal": 5},
  "dark blue": {"clear tan": 5, "clear silver": 5, "drab black": 3},
  "plaid coral": {"plaid aqua": 2, "drab gold": 3, "mirrored plum": 5, "dim bronze": 2},
  "light maroon": {"dim yellow": 3, "light red": 1},
  "plaid silver": {"pale maroon": 1, "shiny black": 5, "dark coral": 2, "posh violet": 3},
  "clear violet": {"vibrant fuchsia": 2},
  "clear cyan": {"plaid yellow": 2, "plaid olive": 4, "dull green": 5},
  "dim magenta": {"wavy plum": 1},
  "drab salmon": {"dull white": 5, "dark brown": 4},
  "pale magenta": {"muted olive": 1, "mirrored fuchsia": 5, "shiny purple": 3},
  "drab coral": {"striped silver": 2},
  "light gold": {"shiny aqua": 4, "dim violet": 5, "dotted orange": 2},
  "shiny cyan": {"muted aqua": 4, "striped maroon": 3, "light salmon": 5},
  "drab beige": {"light gold": 4, "dull white": 5},
  "plaid fuchsia": {},
  "vibrant teal": {"muted maroon": 4, "posh violet": 5, "clear tan": 2, "dull orange": 1},
  "dim cyan": {"dark turquoise": 1},
  "mirrored chartreuse": {"dull lavender": 1, "pale red": 4, "plaid chartreuse": 4},
  "plaid gold": {"dark turquoise": 5, "dim turquoise": 4, "plaid fuchsia": 4},
  "wavy gold": {"light lime": 2, "wavy tomato": 5},
  "wavy red": {"dotted lavender": 4, "dotted blue": 3, "striped brown": 4, "faded orange": 2},
  "dull red": {"drab green": 5},
  "light red": {"dark coral": 2},
  "wavy crimson": {"shiny gold": 2, "drab white": 1},
  "drab turquoise": {"posh gold": 4, "pale plum": 2, "wavy beige": 3, "drab beige": 2},
  "dim lavender": {"dark olive": 4},
  "shiny tan": {"shiny teal": 1, "clear tan": 1, "wavy beige": 4, "posh coral": 5},
  "mirrored fuchsia": {"bright brown": 3},
  "clear white": {"bright cyan": 2, "pale orange": 1, "vibrant gold": 3, "dim cyan": 3},
  "clear magenta": {"dull violet": 3, "dull coral": 2, "dull olive": 1, "pale cyan": 1},
  "mirrored salmon": {"drab gray": 5, "striped magenta": 1},
  "vibrant crimson": {"shiny aqua": 4, "faded bronze": 5},
  "clear yellow": {"bright beige": 3},
  "striped olive": {"clear silver": 2, "dim orange": 5, "posh black": 2, "striped lavender": 2},
  "pale olive": {"dotted blue": 3, "faded indigo": 2, "pale crimson": 3, "clear tan": 4},
  "striped white": {"drab silver": 2, "clear brown": 2},
  "dotted chartreuse": {"dark brown": 4, "dim maroon": 4, "plaid chartreuse": 3, "dark red": 2},
  "dim fuchsia": {"posh indigo": 3, "clear purple": 5},
  "shiny lime": {"muted gold": 3, "vibrant crimson": 3, "mirrored green": 3},
  "striped blue": {"clear coral": 2, "drab green": 4, "dull green": 2},
  "shiny beige": {"wavy lime": 3},
  "dim tan": {"clear green": 2, "dull green": 2},
  "posh cyan": {"faded purple": 4},
  "striped violet": {"faded orange": 2, "plaid crimson": 5, "dull fuchsia": 2, "bright black": 2},
  "mirrored crimson": {"drab gray": 1, "faded crimson": 3, "dim white": 2, "dull green": 4},
  "dim orange": {"dim lime": 4, "drab black": 1},
  "drab cyan": {"shiny salmon": 2, "muted plum": 4, "dotted lavender": 4, "plaid gray": 2},
  "drab brown": {"muted purple": 2},
  "mirrored white": {"mirrored crimson": 4, "pale plum": 5, "bright maroon": 2},
  "vibrant silver": {"dark bronze": 3, "light olive": 2, "posh cyan": 3},
  "wavy magenta": {"muted aqua": 3, "clear beige": 3, "drab beige": 5, "faded teal": 1},
  "striped purple": {"pale crimson": 3, "bright maroon": 1, "striped bronze": 2, "pale gold": 4},
  "dark teal": {"shiny aqua": 4, "dull white": 1, "dotted orange": 2, "dull green": 2},
  "dotted coral": {"dark turquoise": 5},
  "vibrant lime": {"dim purple": 3, "shiny black": 5, "dotted black": 3, "mirrored coral": 1},
  "bright gold": {"posh tan": 3, "drab gray": 4, "dotted maroon": 1, "clear fuchsia": 2},
  "dark fuchsia": {"dull yellow": 2, "dim orange": 1, "muted beige": 4},
  "muted tomato": {"posh teal": 1, "shiny olive": 5},
  "dull indigo": {"muted maroon": 4},
  "bright purple": {"dotted olive": 1, "wavy chartreuse": 1, "clear tan": 1, "dotted green": 2},
  "wavy violet": {"striped silver": 3, "pale plum": 1},
  "shiny orange": {"drab black": 2, "drab lime": 3, "shiny black": 2, "faded purple": 4},
  "light beige": {"dim coral": 5, "dark white": 1, "light crimson": 1, "mirrored coral": 3},
  "drab tomato": {"shiny teal": 5, "drab beige": 2, "shiny purple": 2},
  "drab lavender": {"striped tomato": 3, "bright brown": 1},
  "shiny plum": {"plaid magenta": 4, "posh indigo": 5, "wavy violet": 1, "clear white": 5},
  "dotted brown": {"mirrored olive": 3, "light yellow": 5, "light tomato": 3},
  "wavy coral": {"mirrored plum": 2, "posh purple": 4},
  "shiny maroon": {"muted cyan": 4, "wavy blue": 1, "clear lime": 2, "plaid orange": 3},
  "posh bronze": {"plaid gold": 1, "posh yellow": 1, "wavy lime": 4, "dull white": 2},
  "bright fuchsia": {"dull silver": 3, "light lime": 2},
  "dull plum": {"dotted salmon": 1, "shiny lavender": 4, "mirrored purple": 5, "bright cyan": 2},
  "bright aqua": {"dull salmon": 5, "plaid crimson": 1, "shiny tomato": 4, "vibrant fuchsia": 5},
  "shiny salmon": {"plaid orange": 4, "drab green": 5},
  "muted coral": {"dull indigo": 4, "pale plum": 4, "dotted black": 5},
  "vibrant salmon": {"dark turquoise": 5, "drab red": 1},
  "dull black": {"dull magenta": 1},
  "plaid white": {"shiny purple": 3},
  "drab green": {"striped maroon": 5, "dark crimson": 4, "faded teal": 1, "dull green": 1},
  "faded purple": {"shiny gold": 4},
  "striped lime": {"striped turquoise": 5, "clear silver": 1},
  "clear black": {"dark beige": 4, "posh black": 3},
  "vibrant purple": {"dark brown": 5},
  "clear beige": {"light teal": 1, "plaid fuchsia": 4},
  "light lime": {"drab gray": 4, "dark white": 1, "drab tomato": 3, "plaid maroon": 2},
  "muted violet": {"posh turquoise": 1, "mirrored white": 4},
  "vibrant olive": {"clear beige": 3},
  "bright salmon": {"plaid orange": 1},
  "drab bronze": {"shiny turquoise": 4, "clear fuchsia": 1},
  "drab plum": {"muted gold": 2, "mirrored turquoise": 5, "faded orange": 5, "bright magenta": 5},
  "dotted turquoise": {"striped maroon": 5, "mirrored violet": 3, "dark fuchsia": 1},
  "wavy olive": {"vibrant maroon": 5, "shiny tan": 3, "vibrant yellow": 5, "dotted silver": 5},
  "wavy tomato": {"pale white": 1, "light yellow": 5},
  "plaid chartreuse": {"drab black": 3},
  "pale chartreuse": {"muted purple": 3, "dull green": 1, "dark brown": 3, "light teal": 5},
  "dotted cyan": {"pale salmon": 2},
  "muted gold": {"plaid silver": 5, "dotted orange": 5},
  "posh orange": {"posh purple": 5, "dark teal": 4, "dotted silver": 4},
  "pale brown": {"faded teal": 2},
  "wavy aqua": {"muted plum": 5, "wavy tomato": 5, "mirrored gold": 3, "drab tan": 5},
  "bright blue": {"clear green": 2},
  "dotted red": {"wavy plum": 4, "muted green": 5},
  "clear tomato": {"bright cyan": 3, "dull gray": 1, "drab maroon": 5, "muted indigo": 4},
  "plaid orange": {"dotted coral": 4, "pale gray": 5, "shiny violet": 5, "pale aqua": 2},
  "muted teal": {"muted maroon": 2, "drab teal": 1, "light teal": 2},
  "wavy blue": {"pale chartreuse": 5, "shiny white": 2, "posh teal": 5},
  "posh teal": {"pale chartreuse": 3},
  "mirrored magenta": {"bright aqua": 1},
  "vibrant orange": {"mirrored magenta": 3, "mirrored violet": 1, "posh indigo": 3, "faded orange": 5},
  "posh black": {"bright red": 5},
  "pale white": {"dark teal": 3, "dotted silver": 1, "clear green": 2},
  "posh tomato": {"shiny yellow": 1, "light black": 3, "drab blue": 2, "wavy crimson": 5},
  "mirrored teal": {"drab gray": 1, "light lime": 4},
  "muted green": {"striped brown": 5},
  "dim gold": {"posh indigo": 2, "clear indigo": 5, "posh gray": 4},
  "dull gray": {"posh orange": 4, "shiny gold": 3, "dim tomato": 1, "bright crimson": 3},
  "striped green": {"dark tan": 4, "drab gray": 2, "mirrored brown": 1},
  "clear coral": {"striped brown": 2, "light lime": 2},
  "posh brown": {"vibrant purple": 3, "dark chartreuse": 3, "shiny cyan": 5},
  "dotted black": {"bright crimson": 2, "posh orange": 3, "light gold": 4, "dark brown": 5},
  "posh chartreuse": {"wavy salmon": 5, "striped silver": 3, "drab violet": 2},
  "mirrored tomato": {"pale crimson": 3},
  "bright yellow": {"shiny coral": 1, "muted blue": 2, "wavy beige": 4},
  "dull salmon": {"bright blue": 3, "dull green": 4, "drab salmon": 5},
  "pale black": {"shiny salmon": 5},
  "drab aqua": {"striped fuchsia": 5, "light lavender": 2, "light magenta": 1},
  "muted yellow": {"striped plum": 4, "faded beige": 2, "dull salmon": 1, "bright red": 5},
  "striped brown": {"bright red": 3, "shiny violet": 3},
  "posh white": {"mirrored violet": 2, "muted silver": 4},
  "posh lavender": {"light crimson": 5, "pale silver": 5, "shiny green": 2, "mirrored silver": 4},
  "plaid beige": {"mirrored silver": 3},
  "dull silver": {"dotted silver": 1, "drab salmon": 1},
  "dark violet": {"dotted green": 3, "muted aqua": 1, "bright chartreuse": 4},
  "dotted maroon": {"clear red": 3, "drab blue": 4, "vibrant gray": 4},
  "dim green": {"dotted silver": 4},
  "vibrant fuchsia": {"shiny violet": 5, "dim violet": 1, "dotted beige": 5},
  "muted salmon": {"dim white": 5},
  "drab orange": {"dark teal": 5},
  "vibrant violet": {"posh cyan": 4, "mirrored brown": 4, "dark beige": 5},
  "bright crimson": {"plaid fuchsia": 1, "drab black": 2},
  "muted plum": {"striped brown": 4, "dull green": 4, "mirrored beige": 4},
  "plaid violet": {"dotted indigo": 4},
  "wavy yellow": {"plaid lime": 3, "mirrored orange": 2},
  "faded teal": {"clear plum": 2, "posh purple": 2, "muted plum": 3, "dim tomato": 2},
  "vibrant brown": {"light tan": 1, "light lime": 1},
  "vibrant turquoise": {"clear bronze": 2, "striped gray": 2, "pale green": 2, "vibrant indigo": 5},
  "dark black": {"mirrored gray": 3},
  "muted orange": {"dull orange": 2},
  "shiny aqua": {"posh turquoise": 1},
  "posh fuchsia": {"shiny fuchsia": 2, "light gold": 5},
  "light plum": {"pale teal": 1, "plaid maroon": 4, "drab maroon": 3},
  "posh plum": {"muted magenta": 4},
  "plaid teal": {"muted gray": 1, "clear bronze": 3, "pale tomato": 5},
  "pale aqua": {"posh turquoise": 4, "light chartreuse": 5, "pale white": 1, "light gold": 5},
  "bright tomato": {"bright yellow": 4, "dark red": 5, "shiny orange": 1, "dim teal": 1},
  "light teal": {},
  "dark olive": {"drab gray": 1, "striped teal": 2},
  "dotted tan": {"shiny salmon": 4, "light black": 2, "bright red": 5},
  "light cyan": {"clear beige": 1, "plaid orange": 4, "wavy lavender": 5},
  "dark indigo": {"mirrored orange": 5, "posh brown": 3},
  "clear fuchsia": {"dark red": 1, "posh black": 2},
  "dotted salmon": {"pale gray": 5},
  "mirrored turquoise": {"light aqua": 1},
  "plaid olive": {"dull silver": 2, "light black": 2},
  "posh crimson": {"drab black": 4, "dim teal": 4, "light cyan": 5, "dark teal": 3},
  "dull lime": {},
  "drab chartreuse": {"faded tan": 1},
  "faded gray": {"dark crimson": 5, "light lavender": 3, "dim silver": 5},
  "wavy indigo": {"muted chartreuse": 3, "dim green": 2, "light fuchsia": 3, "shiny white": 3},
  "light tan": {"light olive": 1, "dim cyan": 1, "plaid orange": 5},
  "light fuchsia": {"shiny indigo": 2, "wavy coral": 5, "wavy tomato": 2},
  "dull yellow": {"faded coral": 4, "dim white": 3, "dull white": 5},
  "drab magenta": {"muted violet": 4, "light plum": 5, "faded orange": 4},
  "mirrored gray": {"wavy cyan": 2, "drab teal": 1, "clear red": 1, "bright lavender": 5},
  "dull coral": {"bright yellow": 1, "dull violet": 5, "dark orange": 5, "bright green": 2},
  "mirrored olive": {"drab plum": 1, "plaid orange": 3},
  "muted olive": {"shiny gold": 5, "shiny aqua": 2, "wavy chartreuse": 5, "wavy lavender": 4},
  "clear gold": {"bright purple": 3, "light cyan": 3, "wavy tomato": 5},
  "plaid green": {"shiny yellow": 4, "light salmon": 2, "light silver": 2, "dim purple": 5},
  "posh red": {"dark violet": 5},
  "muted purple": {"drab salmon": 3},
  "vibrant aqua": {"clear beige": 5, "vibrant silver": 3, "faded olive": 1},
  "striped indigo": {"plaid brown": 3, "light aqua": 4, "pale tomato": 3},
  "wavy tan": {"faded indigo": 2, "vibrant chartreuse": 1, "drab beige": 5, "drab gold": 4},
  "shiny gold": {"wavy chartreuse": 5},
  "wavy purple": {"faded maroon": 5, "pale magenta": 4},
  "mirrored indigo": {"plaid black": 2, "dark teal": 5, "dull indigo": 2},
  "plaid crimson": {"dotted green": 5, "dull white": 2},
  "dark aqua": {"wavy coral": 1, "plaid crimson": 1},
  "shiny fuchsia": {"dark olive": 1, "wavy silver": 4, "bright turquoise": 2, "dull white": 1},
  "striped orange": {"dotted green": 4, "mirrored coral": 1, "dull indigo": 5},
  "drab purple": {"posh orange": 1, "bright blue": 1},
  "dull orange": {"dim indigo": 3, "pale orange": 3},
  "pale plum": {"light yellow": 2},
  "pale cyan": {"drab salmon": 4, "dull magenta": 3, "clear plum": 1, "faded tomato": 1},
  "dotted indigo": {"mirrored beige": 1, "drab black": 1, "shiny aqua": 4},
  "shiny lavender": {"muted beige": 1, "bright cyan": 5, "dull green": 2},
  "drab lime": {"drab black": 5, "dotted salmon": 4},
  "mirrored bronze": {"dim bronze": 3, "striped tan": 3, "clear maroon": 4, "dotted coral": 4},
  "shiny brown": {"striped gold": 4, "vibrant silver": 1, "shiny gold": 3},
  "striped chartreuse": {"vibrant gray": 5, "dark cyan": 1},
  "muted black": {"plaid indigo": 4},
  "muted aqua": {"pale red": 1, "pale aqua": 5},
  "bright maroon": {"drab black": 2, "clear violet": 1, "dotted lavender": 1, "mirrored turquoise": 1},
  "vibrant chartreuse": {"pale silver": 5},
  "dull purple": {"mirrored chartreuse": 2},
  "clear brown": {"light coral": 2, "plaid cyan": 4, "dim brown": 3},
  "shiny teal": {"drab black": 5, "shiny silver": 2, "muted purple": 3},
  "dull aqua": {"dotted lime": 5, "mirrored lime": 4},
  "wavy green": {"striped brown": 1, "striped turquoise": 2, "dull silver": 4, "drab white": 3},
  "clear gray": {"pale tan": 5, "posh tomato": 4, "dark brown": 3, "striped violet": 1},
  "bright cyan": {"drab salmon": 5, "light crimson": 5},
  "clear silver": {"mirrored turquoise": 4, "posh orange": 4, "light gold": 3, "clear green": 4},
  "pale purple": {"dotted beige": 5, "posh orange": 5},
  "striped tomato": {"dotted green": 1, "dark turquoise": 4},
  "muted tan": {"faded green": 2, "dim cyan": 3},
  "dark coral": {"dim chartreuse": 2, "striped plum": 1},
  "shiny white": {"posh orange": 2},
  "dim olive": {"faded teal": 1, "pale lime": 4, "dim teal": 3},
  "faded black": {"pale cyan": 4, "dull gray": 3, "light teal": 5, "shiny bronze": 4},
  "light indigo": {"dim cyan": 3, "shiny silver": 1, "dull lavender": 5},
  "dim coral": {"striped silver": 2, "dim tomato": 4},
  "plaid tan": {"mirrored turquoise": 2, "dim beige": 4, "shiny lavender": 5, "dim bronze": 4},
  "striped plum": {"wavy lavender": 2, "drab white": 1},
  "faded white": {"dim coral": 1},
  "dotted lime": {"muted gold": 2, "shiny violet": 5, "plaid violet": 5, "wavy bronze": 1},
  "dotted violet": {"posh orange": 1, "plaid fuchsia": 2},
  "dull gold": {"vibrant crimson": 5, "drab bronze": 1, "dotted tan": 3},
  "bright red": {"pale white": 4, "light chartreuse": 4, "clear beige": 3, "dotted green": 5},
  "wavy cyan": {"dotted chartreuse": 5, "wavy violet": 1, "posh coral": 1, "dotted bronze": 5},
  "faded fuchsia": {"posh maroon": 3, "clear plum": 4, "drab lime": 3},
  "dim violet": {},
  "striped bronze": {"dim orange": 2, "dark orange": 1, "dark salmon": 1, "faded teal": 4},
  "drab olive": {"striped violet": 2, "pale beige": 2},
  "muted red": {"pale aqua": 5, "wavy cyan": 1, "clear white": 4, "drab red": 1},
  "shiny blue": {"plaid aqua": 5, "drab salmon": 2, "pale tan": 5, "vibrant cyan": 4},
  "dotted olive": {"dark brown": 5},
  "shiny silver": {"light gold": 3, "bright crimson": 5, "dark turquoise": 4},
  "dark beige": {"mirrored red": 1, "dark salmon": 3, "striped silver": 5, "plaid orange": 3},
  "plaid red": {"wavy fuchsia": 2, "shiny turquoise": 2, "shiny coral": 1},
  "mirrored beige": {"plaid crimson": 1, "dotted beige": 4, "clear beige": 2, "muted blue": 2},
  "dim plum": {"striped cyan": 4, "shiny beige": 5, "vibrant olive": 2, "light maroon": 4},
  "dotted beige": {"shiny violet": 3, "dim violet": 5, "dull white": 5, "plaid fuchsia": 2},
  "pale beige": {"light aqua": 2},
  "dim gray": {"dotted indigo": 4, "dim coral": 4},
  "light purple": {"shiny brown": 5, "drab violet": 2, "striped tomato": 1},
  "dark salmon": {"dim green": 1, "dim tan": 5},
  "mirrored lime": {"light gold": 5, "drab tan": 5},
  "clear blue": {"drab tomato": 3, "pale olive": 3},
  "plaid lavender": {"shiny indigo": 5, "muted crimson": 3, "mirrored lime": 5},
  "vibrant tomato": {"drab salmon": 3, "faded purple": 5, "faded bronze": 1, "bright fuchsia": 4},
  "posh turquoise": {"dim chartreuse": 1},
  "clear turquoise": {"muted indigo": 4, "dark maroon": 1, "dull coral": 4},
  "drab crimson": {"plaid turquoise": 1, "faded salmon": 2},
  "dark brown": {},
  "faded tomato": {"light cyan": 2, "light maroon": 1},
  "clear plum": {"drab lavender": 2},
  "bright white": {"dim tan": 2, "faded orange": 1, "dim aqua": 1},
  "shiny green": {"dotted coral": 3, "mirrored white": 1, "shiny gray": 3},
  "clear olive": {"mirrored teal": 3},
  "striped red": {"pale green": 1, "light maroon": 4},
  "dull tomato": {"mirrored white": 3, "posh bronze": 4},
  "light silver": {"mirrored plum": 1, "dim teal": 2},
  "striped teal": {"light bronze": 4},
  "mirrored tan": {"light gold": 5, "posh brown": 2},
  "clear purple": {"clear magenta": 5, "pale tomato": 2, "light black": 2},
  "faded green": {"light green": 5, "plaid bronze": 5},
  "shiny red": {"dark white": 3, "posh green": 2, "shiny indigo": 2},
  "muted white": {"dotted coral": 4, "wavy blue": 5},
  "dim crimson": {"wavy blue": 3, "pale gray": 2},
  "striped lavender": {"dark blue": 2, "pale aqua": 2, "striped turquoise": 5, "dark coral": 3},
  "wavy gray": {"muted gray": 2, "pale silver": 1, "muted blue": 5, "pale tomato": 5},
  "mirrored silver": {"mirrored black": 2, "mirrored plum": 5, "striped silver": 5, "dotted green": 3},
  "light crimson": {"faded maroon": 4, "dim chartreuse": 4, "dotted violet": 5},
  "shiny coral": {"shiny silver": 4, "posh yellow": 3, "plaid blue": 5, "shiny aqua": 3},
  "pale red": {"drab white": 4, "dotted silver": 1, "drab salmon": 4, "dull green": 3},
  "posh maroon": {"dim green": 1},
  "posh gold": {"pale green": 1, "striped silver": 5},
  "light blue": {"dotted silver": 2, "muted beige": 1},
  "pale lavender": {"vibrant orange": 5, "dull chartreuse": 2},
  "faded gold": {"shiny gray": 2},
  "bright orange": {"posh teal": 3, "wavy green": 5, "bright chartreuse": 1, "dark white": 5},
  "mirrored violet": {"pale white": 2, "dark brown": 5, "bright blue": 5},
  "dim white": {"clear green": 4},
  "light aqua": {},
  "dull chartreuse": {"striped gold": 5},
  "clear salmon": {"pale salmon": 5},
  "bright olive": {"posh blue": 1},
  "bright lavender": {"pale lime": 2},
  "pale turquoise": {"muted chartreuse": 3},
  "vibrant white": {"light red": 5},
  "dotted silver": {"dark brown": 1, "dark turquoise": 5, "dim violet": 4},
  "dull green": {"light teal": 2, "drab black": 5},
  "wavy plum": {"pale indigo": 4, "plaid yellow": 3, "wavy green": 1, "muted green": 4},
  "vibrant yellow": {"bright beige": 2, "dim brown": 2, "dotted teal": 3},
  "faded beige": {"dim brown": 3, "clear gold": 4},
  "dotted purple": {"shiny white": 4},
  "mirrored green": {"dark red": 5, "drab violet": 4, "bright lavender": 3},
  "shiny tomato": {"striped lavender": 3},
  "bright silver": {"dotted magenta": 1, "dim green": 3, "muted coral": 1, "shiny teal": 4},
  "plaid maroon": {"dim brown": 5},
  "dim salmon": {"pale olive": 4, "dark crimson": 5},
  "dark gold": {"dark orange": 3, "bright fuchsia": 3, "dull salmon": 1, "dark blue": 5},
  "striped cyan": {"plaid blue": 3, "dark orange": 1, "clear violet": 5},
  "dark gray": {"light orange": 5},
  "posh gray": {"plaid maroon": 1, "drab gold": 4, "muted gold": 1, "light bronze": 4},
  "pale gold": {"clear orange": 4, "dim orange": 5},
  "pale teal": {"posh teal": 1, "pale red": 5},
  "vibrant lavender": {"plaid silver": 5, "clear orange": 3, "posh silver": 2, "wavy violet": 1},
  "dim black": {"dark plum": 2, "plaid turquoise": 2, "dull salmon": 3, "clear orange": 2},
  "dark white": {"vibrant fuchsia": 2},
  "dark red": {"shiny violet": 3, "vibrant fuchsia": 5, "pale crimson": 1},
  "striped silver": {"posh purple": 2, "dark white": 4},
  "striped turquoise": {"bright brown": 1, "dotted green": 2},
  "wavy salmon": {"light teal": 5},
  "muted turquoise": {"bright gray": 1, "plaid orange": 2, "muted blue": 5, "dotted olive": 2},
  "wavy black": {"mirrored black": 2, "striped plum": 2, "dull lime": 1, "posh teal": 4},
  "striped tan": {"pale green": 5},
  "dark turquoise": {"shiny violet": 5, "dark brown": 3},
  "plaid black": {"plaid crimson": 5, "dim turquoise": 2, "dotted black": 4},
  "light turquoise": {"plaid chartreuse": 4, "dull violet": 4},
  "plaid gray": {"light yellow": 1, "striped lavender": 4, "wavy chartreuse": 4, "dotted salmon": 3},
  "drab black": {},
  "plaid cyan": {"dim tan": 1, "plaid gold": 2, "drab gray": 1},
  "bright tan": {"plaid olive": 1, "mirrored black": 3},
  "faded brown": {"dotted tomato": 2},
  "dotted fuchsia": {"drab silver": 5},
  "drab white": {"shiny violet": 5},
  "posh salmon": {"striped turquoise": 3},
  "dull maroon": {"faded indigo": 2},
  "bright bronze": {"muted blue": 1, "dark chartreuse": 5, "wavy purple": 2, "vibrant violet": 3},
  "plaid bronze": {"dark brown": 1},
  "dark lavender": {"dim yellow": 3, "drab red": 4, "bright turquoise": 2, "shiny black": 4},
  "wavy silver": {"light yellow": 1, "pale red": 2},
  "pale tan": {"dull orange": 5, "dotted olive": 5, "vibrant purple": 2, "dull tan": 4},
  "pale orange": {"light teal": 3, "dim maroon": 1},
  "shiny indigo": {"drab maroon": 3, "dotted indigo": 2, "bright purple": 1, "striped brown": 2},
  "muted fuchsia": {"posh crimson": 4, "clear beige": 3},
  "plaid plum": {"clear silver": 1, "light cyan": 4, "vibrant gray": 1, "drab purple": 5},
  "faded violet": {"dotted beige": 3, "muted aqua": 3},
  "dotted plum": {"plaid brown": 4, "wavy green": 5, "dark cyan": 3, "pale red": 2},
  "vibrant tan": {"clear gray": 4},
  "drab silver": {"dull chartreuse": 3},
  "shiny turquoise": {"dark olive": 4},
  "dark silver": {"dotted black": 2},
  "striped beige": {"striped magenta": 5},
  "dotted orange": {"light aqua": 1, "posh turquoise": 4},
  "shiny magenta": {"drab salmon": 3, "mirrored orange": 5},
  "posh magenta": {"plaid fuchsia": 3, "dim maroon": 4},
  "clear bronze": {"wavy fuchsia": 1, "vibrant black": 2},
  "dull violet": {"muted indigo": 1, "posh green": 2, "striped white": 4, "clear red": 1},
  "posh lime": {"vibrant cyan": 5},
  "pale silver": {"dark crimson": 2, "light salmon": 1, "clear brown": 1},
  "posh yellow": {"dim white": 1, "pale crimson": 2},
  "vibrant bronze": {"faded gray": 4, "dim gray": 1, "posh cyan": 2, "plaid lavender": 4},
  "dull beige": {"wavy fuchsia": 4, "plaid crimson": 4, "dark blue": 2, "wavy silver": 1},
  "dull brown": {"pale turquoise": 4, "clear tan": 4},
  "faded turquoise": {"plaid gold": 5, "wavy chartreuse": 4},
  "dark yellow": {"wavy lavender": 1, "dark coral": 5},
  "dotted gray": {"posh purple": 4, "wavy lavender": 5, "shiny green": 5, "plaid white": 5},
  "dim aqua": {"dull lime": 1},
  "posh violet": {"mirrored tomato": 1, "posh cyan": 3},
  "shiny gray": {"clear green": 3, "wavy bronze": 1, "dark turquoise": 4, "pale white": 3},
  "drab red": {"mirrored violet": 2, "dotted orange": 3, "dark lime": 5, "bright purple": 4},
  "striped magenta": {"striped brown": 3},
  "dull magenta": {"dim tomato": 4, "muted beige": 3, "clear violet": 5},
  "clear maroon": {"plaid lime": 4},
  "posh silver": {"mirrored red": 3},
  "dark crimson": {"mirrored violet": 2},
  "pale maroon": {"shiny black": 2},
  "dark magenta": {"dark green": 1, "light plum": 4},
  "bright lime": {"pale indigo": 1, "dim yellow": 3, "drab maroon": 2, "light plum": 4},
  "dark orange": {"wavy lavender": 1, "dotted orange": 1, "light crimson": 2, "light yellow": 3},
  "wavy lime": {"clear blue": 4, "muted brown": 2, "mirrored violet": 2, "dotted lavender": 2},
  "dotted lavender": {"posh teal": 1, "dark red": 5, "pale gray": 1},
  "muted brown": {"dark white": 1, "dull maroon": 2, "faded maroon": 1},
  "dim yellow": {"dark white": 5},
  "faded tan": {"light coral": 4, "light yellow": 4},
  "faded crimson": {"plaid fuchsia": 3, "plaid orange": 5},
  "pale salmon": {"pale red": 5, "dotted olive": 4, "plaid magenta": 3},
  "dim bronze": {"muted plum": 4, "light cyan": 3, "dark coral": 3},
  "bright teal": {"vibrant violet": 2, "striped bronze": 4, "striped violet": 1, "dark gray": 2},
  "pale bronze": {"plaid brown": 2, "plaid white": 1},
  "vibrant plum": {"drab tan": 2, "plaid yellow": 2, "faded fuchsia": 3},
  "dotted teal": {"faded coral": 5, "faded indigo": 5, "posh violet": 1, "pale indigo": 3},
  "plaid salmon": {"dark lavender": 2, "posh bronze": 3, "light coral": 4, "posh orange": 1},
  "dim red": {"light violet": 3},
  "drab gold": {"wavy silver": 4, "light bronze": 5},
  "shiny violet": {},
  "mirrored maroon": {"drab yellow": 1, "wavy beige": 5},
  "dotted aqua": {"muted plum": 4},
  "faded salmon": {"mirrored olive": 4, "dim lavender": 5},
  "light violet": {"wavy salmon": 2},
  "plaid brown": {"faded indigo": 5},
  "mirrored coral": {"pale gray": 4},
  "muted lavender": {"posh beige": 1, "clear silver": 2, "dotted bronze": 1},
  "bright turquoise": {"striped black": 2, "dull maroon": 3},
  "vibrant gold": {"bright purple": 5, "bright red": 1},
  "muted magenta": {"clear violet": 1, "muted lavender": 5, "faded aqua": 4},
  "faded silver": {"posh brown": 4, "mirrored silver": 2},
  "dim teal": {"dim violet": 2, "dark white": 1, "dotted black": 2},
  "striped maroon": {"shiny white": 5},
  "dark maroon": {"plaid silver": 2, "dull red": 1, "shiny coral": 2, "bright white": 5},
  "clear crimson": {"muted salmon": 4, "clear green": 5, "light blue": 1, "posh magenta": 5},
  "dotted yellow": {"vibrant coral": 3},
  "light tomato": {"dim chartreuse": 4, "light gold": 4, "dark white": 5},
  "shiny purple": {"dark turquoise": 3},
  "bright green": {"light chartreuse": 1},
  "mirrored yellow": {"striped white": 4},
  "light lavender": {"wavy crimson": 1, "dim yellow": 3, "plaid olive": 1, "wavy white": 5},
  "muted crimson": {"dark beige": 2, "dull green": 1},
  "muted blue": {"shiny aqua": 3, "dark turquoise": 5, "dotted silver": 1},
  "striped coral": {"dark red": 2, "drab blue": 1, "light aqua": 2, "striped lavender": 1},
  "light brown": {"plaid yellow": 4},
  "clear aqua": {"plaid olive": 1, "plaid gold": 1, "muted tan": 1},
  "dotted gold": {"dark white": 2},
  "plaid blue": {"dotted coral": 5, "muted blue": 3},
  "mirrored cyan": {"dark white": 3, "striped turquoise": 1, "light coral": 3},
  "faded red": {"clear tan": 3, "striped brown": 5, "shiny cyan": 3},
  "clear lime": {"clear silver": 4},
  "dim lime": {"light teal": 2, "posh turquoise": 1, "dotted silver": 3, "drab lavender": 1},
  "dull teal": {"light maroon": 1, "bright coral": 4},
  "light gray": {"mirrored lime": 5, "light violet": 3, "muted olive": 1, "striped brown": 4},
  "dotted white": {"wavy white": 3, "dotted beige": 1, "clear green": 5},
  "shiny crimson": {"pale salmon": 3, "dark lime": 3, "dull blue": 4, "vibrant chartreuse": 1},
  "dim brown": {"mirrored beige": 5, "light orange": 5, "faded crimson": 2},
  "dim blue": {"pale gray": 5},
  "striped black": {"vibrant purple": 2, "vibrant salmon": 4, "clear gold": 2, "shiny yellow": 3},
  "striped fuchsia": {"plaid fuchsia": 3, "posh teal": 4, "drab tomato": 5, "dim turquoise": 3},
  "shiny black": {"striped tomato": 2},
  "vibrant maroon": {"bright aqua": 5, "posh white": 1, "pale silver": 1, "muted tan": 2},
  "posh coral": {"mirrored violet": 2, "mirrored beige": 2, "striped tomato": 4, "drab white": 2},
  "wavy chartreuse": {"muted blue": 5, "bright crimson": 1, "pale gray": 1, "shiny silver": 1},
  "bright chartreuse": {"striped brown": 5},
  "bright gray": {"drab gray": 3, "plaid cyan": 4, "drab maroon": 1},
  "dark lime": {"clear green": 4, "dotted white": 4},
  "faded maroon": {"shiny gold": 5, "dotted green": 4, "striped brown": 2},
  "dim silver": {"muted tomato": 5, "mirrored violet": 5},
  "faded chartreuse": {"pale gray": 2, "striped cyan": 3},
  "posh beige": {"faded blue": 3},
  "striped aqua": {"bright gray": 5, "shiny aqua": 4, "shiny gray": 3},
  "dull tan": {"dotted green": 2, "light crimson": 3, "mirrored fuchsia": 3, "shiny cyan": 5},
  "dark green": {"drab yellow": 2},
  "wavy fuchsia": {"wavy gray": 2, "faded fuchsia": 1, "bright maroon": 5},
  "vibrant indigo": {"dotted tomato": 5, "light coral": 4, "dark silver": 1},
  "drab indigo": {"pale coral": 5},
  "faded indigo": {"vibrant fuchsia": 5, "wavy coral": 1, "striped teal": 3},
  "pale violet": {"pale lime": 3, "posh indigo": 2, "muted blue": 5, "plaid cyan": 2},
  "drab blue": {"dull silver": 3, "dotted beige": 2, "muted aqua": 1, "dotted orange": 3},
  "dull crimson": {"dim brown": 2, "mirrored black": 1},
  "mirrored lavender": {"posh chartreuse": 2, "vibrant blue": 1, "dull magenta": 5},
  "light olive": {"dotted silver": 5, "dim white": 5, "pale teal": 5},
  "vibrant blue": {"dark fuchsia": 1, "dim teal": 5},
  "dim chartreuse": {},
  "bright black": {"dull lavender": 1, "dark teal": 3, "plaid blue": 2, "dark white": 5},
  "dark cyan": {"light beige": 5, "bright orange": 5},
  "light yellow": {"striped silver": 5, "dark brown": 2, "dotted salmon": 2, "dim violet": 4},
  "dotted bronze": {"dim blue": 5, "dark chartreuse": 2},
  "faded yellow": {"faded fuchsia": 1, "dark brown": 4, "muted salmon": 1},
  "dull fuchsia": {"bright turquoise": 1, "drab green": 1},
  "faded blue": {"dull chartreuse": 5, "shiny violet": 1},
  "striped gold": {"dull silver": 2, "dotted black": 4},
  "mirrored black": {"wavy tomato": 1, "posh violet": 3, "vibrant crimson": 4, "dull lime": 1},
  "posh tan": {"plaid olive": 2, "dotted white": 5},
  "vibrant black": {"light chartreuse": 1, "dark orange": 2},
  "dim indigo": {"plaid crimson": 1},
  "mirrored red": {"faded maroon": 4},
  "vibrant beige": {"faded teal": 5, "shiny coral": 5, "drab teal": 4},
  "drab gray": {"light teal": 4, "dull white": 1},
  "pale blue": {"posh purple": 1, "light cyan": 4},
  "posh indigo": {"dim gray": 4, "striped maroon": 2, "drab white": 4, "light tomato": 3},
  "dim maroon": {"pale white": 3},
  "faded aqua": {"drab white": 2, "faded purple": 3, "striped maroon": 4},
  "plaid aqua": {"striped turquoise": 1, "light bronze": 4, "pale chartreuse": 3},
  "dull lavender": {"striped plum": 5, "dotted white": 1, "dotted salmon": 2, "dull silver": 5},
  "light magenta": {"drab violet": 2, "drab coral": 5, "vibrant lavender": 2, "dull olive": 3},
  "faded lime": {"mirrored coral": 3, "wavy lavender": 2, "light yellow": 3, "shiny silver": 1},
  "wavy white": {"drab white": 4},
  "clear indigo": {"dim cyan": 3},
  "plaid turquoise": {"drab white": 4, "dark teal": 3, "plaid fuchsia": 2},
  "plaid tomato": {"drab violet": 3, "striped salmon": 5},
  "bright beige": {"shiny black": 5, "posh salmon": 5, "striped bronze": 4, "pale plum": 3},
  "vibrant red": {"pale fuchsia": 4},
  "posh green": {"drab red": 1},
  "faded plum": {"plaid chartreuse": 5, "bright bronze": 5, "dark blue": 4, "clear bronze": 3},
  "dim turquoise": {"light chartreuse": 3},
  "clear red": {"drab blue": 1, "striped fuchsia": 5, "striped brown": 5, "clear silver": 3},
  "pale gray": {"dull green": 1, "dotted orange": 2, "dark turquoise": 2},
  "plaid purple": {"dim cyan": 1, "striped lime": 4, "drab violet": 3},
  "clear teal": {"dull cyan": 2, "wavy cyan": 1, "light blue": 2},
  "mirrored brown": {"mirrored red": 5},
  "light bronze": {"wavy white": 1},
  "muted gray": {"faded lime": 5, "pale beige": 1, "shiny indigo": 1, "faded tan": 1},
  "striped salmon": {"dim teal": 5, "dotted silver": 5, "dim gray": 5},
  "bright indigo": {"drab beige": 3, "shiny red": 1, "vibrant silver": 4, "clear plum": 4},
  "pale coral": {"wavy plum": 5, "clear beige": 2},
  "faded olive": {"bright crimson": 2, "dotted green": 5, "dull bronze": 5, "posh turquoise": 2},
  "wavy maroon": {"mirrored fuchsia": 5, "dim olive": 5},
  "plaid indigo": {"posh magenta": 5, "dim bronze": 1, "light blue": 1},
  "posh aqua": {"clear beige": 5, "dark lime": 3},
  "faded cyan": {"drab tomato": 1, "posh crimson": 4, "pale chartreuse": 5, "faded tan": 3},
  "plaid yellow": {"wavy cyan": 3, "striped black": 3},
  "faded magenta": {"bright coral": 4},
  "dull cyan": {"mirrored magenta": 4, "clear chartreuse": 3},
  "vibrant coral": {"dotted aqua": 2, "bright cyan": 1},
  "mirrored gold": {"shiny purple": 2},
  "mirrored purple": {"dark beige": 3},
  "pale yellow": {"plaid coral": 5, "wavy silver": 3, "mirrored salmon": 1, "light lime": 3},
  "dark tan": {"light yellow": 1, "plaid turquoise": 5, "shiny gold": 4},
  "faded bronze": {"striped gold": 5, "posh teal": 1},
  "light black": {"shiny black": 2, "mirrored coral": 2},
  "vibrant gray": {"dark teal": 5, "muted aqua": 3, "shiny violet": 4, "dark bronze": 5},
  "wavy beige": {"pale maroon": 2},
  "muted silver": {"plaid orange": 4, "shiny chartreuse": 1},
  "plaid magenta": {"dotted tan": 1, "striped fuchsia": 3, "light olive": 5},
  "drab fuchsia": {"dark violet": 5, "shiny gold": 1, "pale cyan": 3},
  "shiny chartreuse": {"dotted violet": 5},
  "pale crimson": {"pale aqua": 3},
  "dull white": {},
  "pale green": {"bright green": 4, "dull lime": 2, "striped lime": 1},
  "muted bronze": {"bright tomato": 5, "light red": 5, "shiny yellow": 2, "dim teal": 2},
  "mirrored aqua": {"dim tomato": 3, "mirrored crimson": 1, "wavy silver": 1},
  "vibrant magenta": {"dark lime": 2}
};

console.log(findInnerBags("shiny gold", regsArray));
